# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Created with https://github.com/StefanScherer/packer-windows/tree/b2a7684f75b533091733ae5fb25609af233e1284
  # packer build --only=virtualbox-iso --var 'iso_url=D:/software/14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO' ./windows_2016_docker.json
  # vagrant box add windows_2016_docker_virtualbox.box   --name windows_2016_docker_virtualbox_rs1_v1
  config.vm.box = "windows_2016_docker_virtualbox_rs1_v1"

  config.vm.synced_folder "../", "/garden-hcs"
  config.vm.network "private_network", ip: "192.168.50.16"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 4
    vb.memory = "4096"
  end

  config.vm.provision "file", source: "install-packages.ps1", destination: "C:\\diego-kit\\intall-packages.ps1"
  config.vm.provision "file", source: "install-diego.ps1", destination: "C:\\diego-kit\\intall-diego.ps1"
  config.vm.provision "file", source: "install-garden.ps1", destination: "C:\\diego-kit\\intall-garden.ps1"

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\intall-packages.ps1
  SHELL

  config.vm.provision :reload

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\intall-diego.ps1
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\intall-garden.ps1
  SHELL
end
