# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin "vagrant-reload"

Vagrant.configure(2) do |config|
  # Created with https://github.com/StefanScherer/packer-windows/tree/00dfa8024827170867dfa915178211f19360aedf
  # packer build --only=virtualbox-iso --var 'iso_url=D:/software/en_windows_server_2016_technical_preview_5_x64_dvd_8512312.iso' ./windows_2016_docker.json
  config.vm.box = "windows_2016_docker"

  config.vm.synced_folder "../", "/garden-hcs"
  config.vm.network "private_network", ip: "192.168.50.16"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 4
    vb.memory = "4096"
  end

  config.vm.provision "file", source: "install-packages.ps1", destination: "C:\\diego-kit\\intall-packages.ps1"
  config.vm.provision "file", source: "install-diego.ps1", destination: "C:\\diego-kit\\intall-diego.ps1"
  config.vm.provision "file", source: "install-garden.ps1", destination: "C:\\diego-kit\\intall-garden.ps1"

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\intall-packages.ps1
  SHELL

  config.vm.provision :reload 

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\intall-diego.ps1
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\intall-garden.ps1
  SHELL
end
